version: "3.8"

services:
  api-proxy-server:
    container_name: api-proxy-server
    image: ccr.ccs.tencentyun.com/open-source-project/api-proxy-server:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.json:/app/config.json:ro
